# Generated by Django 2.1.7 on 2020-04-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('post_code', models.CharField(blank=True, max_length=128)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('abbreviation', models.CharField(blank=True, max_length=30)),
                ('issn', models.CharField(max_length=128)),
                ('issn_online', models.CharField(blank=True, max_length=128)),
                ('journal_type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(max_length=128)),
                ('abstract', models.TextField(blank=True)),
                ('article_type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateField(blank=True)),
                ('published_online', models.DateField(blank=True)),
                ('file', models.FilePathField(blank=True, path='/Users/cameron/Development/camrobjones/papernet/papers')),
                ('volume', models.CharField(blank=True, max_length=128)),
                ('issue', models.CharField(blank=True, max_length=128)),
                ('pages', models.CharField(blank=True, max_length=128)),
                ('source', models.URLField(blank=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Journal')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=128)),
                ('journal', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('publication_year', models.CharField(blank=True, max_length=128)),
                ('cited_paper', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cited_by', to='papernet.Paper')),
                ('citing_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='papernet.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='authorship',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Paper'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='authorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Authorship'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Institution'),
        ),
    ]
