# Generated by Django 2.1.7 on 2020-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
