# Generated by Django 2.1.7 on 2020-04-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0002_auto_20200414_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='retrieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='doi',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='position',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='cited_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cited_by', to='papernet.Paper'),
        ),
    ]
