# Generated by Django 3.1.1 on 2020-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0002_auto_20200921_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
