# Generated by Django 3.1.1 on 2020-09-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0003_auto_20200921_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='ua_header',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='wait',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='papernet/sources/')),
                ('file_type', models.CharField(default='raw', max_length=128)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.requestlog')),
            ],
        ),
    ]
