# Generated by Django 3.1.1 on 2020-09-25 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0004_auto_20200921_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.requestlog')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.sourcelog')),
            ],
        ),
    ]
