# Generated by Django 2.1.7 on 2020-04-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0004_reference_cit_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FilePathField(blank=True, null=True, path='/Users/cameron/Development/camrobjones/papernet/papers'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_online',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
