# Generated by Django 3.1.1 on 2020-09-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('papernet', '0005_attribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='model',
        ),
        migrations.AddField(
            model_name='attribution',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
