# Generated by Django 2.1.7 on 2020-05-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0005_auto_20200415_0033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('citing_paper', 'cited_paper')},
        ),
    ]
