# Generated by Django 3.1.1 on 2022-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0006_auto_20200925_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='oci',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
