# Generated by Django 2.1.7 on 2020-09-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0006_auto_20200530_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
