# Generated by Django 2.1.7 on 2020-09-03 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papernet', '0007_paper_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='papernet/default.svg', upload_to='papernet/')),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Readership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=150)),
                ('status_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('readership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Readership')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='papernet/publications/'),
        ),
        migrations.AddField(
            model_name='readership',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Paper'),
        ),
        migrations.AddField(
            model_name='readership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Project'),
        ),
        migrations.AddField(
            model_name='readership',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Reader'),
        ),
        migrations.AddField(
            model_name='project',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.Reader'),
        ),
    ]
