# Generated by Django 2.1.7 on 2020-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0010_auto_20200903_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='image',
            field=models.ImageField(default='papernet/guest.jpg', upload_to='papernet/'),
        ),
    ]
