# Generated by Django 2.1.7 on 2020-09-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0012_auto_20200903_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('ua_header', models.CharField(max_length=200)),
                ('params', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('delta', models.FloatField(default=0)),
                ('response_code', models.IntegerField(default=0)),
            ],
        ),
    ]
