# Generated by Django 2.1.7 on 2020-09-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0013_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='wait',
            field=models.IntegerField(default=0),
        ),
    ]
