# Generated by Django 2.1.7 on 2020-09-05 09:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('papernet', '0014_auto_20200904_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Readership',
            new_name='Perusal',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='readership',
            new_name='perusal',
        ),
    ]
