# Generated by Django 2.1.7 on 2020-09-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0015_auto_20200905_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusal',
            name='status',
            field=models.CharField(blank=True, default='None', max_length=150),
        ),
    ]
