# Generated by Django 3.1.1 on 2020-09-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0019_auto_20200916_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_referenced_by_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='references_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='retrieved',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
