# Generated by Django 3.1.1 on 2020-09-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0020_auto_20200916_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='published_print',
            field=models.DateField(blank=True, null=True),
        ),
    ]
