# Generated by Django 3.1.1 on 2020-09-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0021_auto_20200916_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
    ]
