# Generated by Django 3.1.1 on 2020-09-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0022_auto_20200916_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='doi',
            new_name='cited_doi',
        ),
    ]
