# Generated by Django 3.1.1 on 2020-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0023_auto_20200916_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='citing_doi',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='cited_doi',
            field=models.CharField(max_length=128),
        ),
    ]
