# Generated by Django 3.1.1 on 2020-09-16 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0024_auto_20200916_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='oci',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='reference',
            name='citing_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='papernet.paper'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('citing_doi', 'cited_doi')},
        ),
    ]
