# Generated by Django 3.1.1 on 2020-09-20 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papernet', '0025_auto_20200916_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, default=None, null=True, upload_to='papernet/files/papers/')),
                ('header', models.TextField(blank=True, default='')),
                ('abstract', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('acknowledgements', models.TextField(blank=True, default='')),
                ('references', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papernet.paper')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulltext', to='papernet.paper')),
            ],
        ),
    ]
